animal-squad/project-s-BE

src/app.module.ts
src/auth/auth.controller.ts
src/auth/auth.guard.ts
src/auth/auth.service.ts
src/auth/google.strategy.ts
src/auth/session.serializer.ts
src/database/database.module.ts
src/main.ts
src/session/init.session.ts
src/user/user.entity.ts
src/user/user.service.ts

로그인시 CORS 에러가 발생하여 관련 값을 조정하였습니다.
페이지 이동 경로를 수정하여 원활한 테스트가 가능하도록 조정하였습니다.
main.ts에서 cors 허용 부분 추가
auth.controller에서 리다이렉트 경로 수정
그 외는 모두 prettier 수정입니다.
#8
resolves #8

#8 로그인 CORS

---

Dockerfile

#14
- 배포를 위한 Dockerfile 작성 
resolves #14

CI/CD: Dockerfile for prod

---

src/auth/google.strategy.ts

callback 경로가 항상 localhost로 이동되는 현상을 수정합니다.
callbackURL 변경

Fix: modify callback URL

---

src/auth/google.strategy.ts

PR dev to main

---

Jenkinsfile

#22
Jenkinsfile 버그 수정
resolves #22

Fix : Jenkinsfile 수정

---

Jenkinsfile

Fix: Jenkinsfile 오타 및 누락

---

Jenkinsfile

#25
- Jenkinsfile 내용 오타 수정
resolves #25

Fix: Jenkinsfile 오타 수정

---

Jenkinsfile

Fix: Jenkinsfile 내용 수정 및 오타 수정

---

Jenkinsfile

Fix: Jenkinsfile 수정

---

Jenkinsfile

#29
- Jenkinsfile에서 pod -> Job으로 변경
resolves #29

Fix: Jenkinsfile 내용 수정

---

Jenkinsfile

#29
- Jenkinsfile 오타 수정
resolves #29

FIx: Jenkinsfile 오타

---

src/bucket/bucket.controller.ts
src/bucket/bucket.module.ts
src/bucket/bucket.service.ts
src/bucket/dto/bucket.dto.ts
src/link/dto/link.dto.ts
src/user/user.exception.ts

bucket 추가 과정에서 수정이 필요한 부분을 수정하였습니다.
- content 타입 변경
- user email이 createBucketDto에 포함되도록 변경
- 제목 미입력시 생성된 날짜로 제목이 생성되도록 변경
- user email을 통해 가입된 유저인지 판별하는 부분 추가
- linkUpdateDto에서 userId 삭제
close #38

#38 Refactor: bucket 추가 부분 수정

---

package.json
pnpm-lock.yaml
src/auth/auth.controller.ts
src/bucket/bucket.controller.ts
src/bucket/bucket.service.ts
src/utils/pagination.dto.ts

사용자의 bucket 목록을 불러오는 기능을 개발하였습니다.
- pagination에 맞는 클래스 선언
- GET API 개발
- 유저의 bucket을 불러오면서 총 buckets의 수를 불러오는 findAll 함수 구현
프론트엔드 경로 수정에 따른 리다이렉션 경로를 수정하였습니다.
bucket.service.ts : DB에서 버킷의 목록과 버킷의 총 수를 불러오는 findAll 함수 개발
bucket.controller.ts: GET API 개발
pagination.dto.ts: 페이지네이션 형식에 맞춰 클래스 구현
auth.controller.ts: 리다이렉션 경로 수정
resolves #43

#43 Feat: 버킷 목록 조회 기능

---

prisma/schema.prisma
src/bucket/bucket.controller.ts
src/bucket/bucket.service.ts
src/user/user.decorater.ts
src/user/user.exception.ts

bucket의 상세 정보를 불러오는 기능을 개발하였습니다.
- bucketId를 통해 bucket의 상세 정보를 불러오는 기능
- 링크의 수를 미리 알기 위해 linkCount 컬럼 추가
- 로그인 상태, 권한 여부 확인을 위한 예외 처리 추가
resolves #44

#44 Feat: bucket 상세 조회 기능

---

src/bucket/bucket.controller.ts
src/bucket/bucket.service.ts

공유여부를 업데이트 하기 위한 기능을 개발하였습니다.
- 특정 버킷의 공유 기능을 업데이트 하는 PUT API 구현
- 공유 기능을 업데이트 하는 함수 구현
- 특정 버킷 조회에서 이미 사용쟈 권한에 대한 검증이 진행되어 추가적인 검증 과정은 구현하지 않았습니다
- 
```typescript
```
resolves #46

#46 Feat: bucket 공유 기능

---

prisma/schema.prisma
src/bucket/bucket.controller.ts
src/bucket/bucket.service.ts
src/link/dto/link.dto.ts
src/link/link.service.ts
src/utils/pagination.dto.ts

공유 기능과 관련하여 수정하였습니다
- 버킷과 링크의 id를 string 타입으로 변경
- 버킷에 대한 정보 반환 시 본인의 bucket인지의 여부를 반환하는 부분을 추가
- pagination에서 이름 수정
```typescript
```
#51

#51 Refactor: 공유 기능 수정

---

src/bucket/bucket.controller.ts
src/bucket/bucket.service.ts
src/user/user.exception.ts

버킷의 수정 기능을 개발하였습니다.
PUT API를 통해 버킷의 제목을 수정할 수 있습니다.
bucket.controller.ts에서 새로운 API 추가
bucket.service.ts에서 버킷의 작성자 여부를 확인하고 업데이트 하는 함수 추가
예외처리 클래스 작성
```typescript
```
#54

#54 Feat: bucket 수정 기능

---

src/bucket/bucket.controller.ts
src/bucket/bucket.exception.ts
src/bucket/bucket.service.ts

bucket의 삭제 기능을 개발하였습니다.
bucket과 해당하는 link가 모두 삭제됩니다.
bucket.controller.ts에서 delete api 추가
bucket.service.ts에서 bucket을 가져오는 로직과 bucket, bucket-link relation, link를 삭제하는 기능 추가
bucket이 존재하지 않는 경우에 대해 예외처리 추가
```typescript
```
#53

#53 Feat: bucket 삭제 기능

---

src/bucket/bucket.service.ts

bucket 복사 시 반환되는 내용을 복사된 링크에서 bucket의 id로 수정하였습니다
```typescript
```
resolves #61

#61 Refactor: bucket 복사에서 반환되는 내용 변경

---

Jenkinsfile

#68
- Jenkinsfile을 수정함.
#68 
resolves #68

#68 CI/CD: Jenkinsfile 수정

---

Dockerfile

#75
- Dockefile 레이어 수정(TZ 설정 추가, pnpm build 한 후 실행하도록 설정)
#75 
resovles #75

#75 CI/CD: Dockerfile 내용 수정

---

src/auth/auth.controller.ts
src/bucket/bucket.controller.ts
src/link/link.controller.ts
src/link/link.service.ts
src/session/init.session.ts
src/user/user.controller.ts
src/user/user.decorator.ts
src/user/user.exception.ts

로그인 관련 처리를 추가하였습니다
바구니 저장시 링크가 제대로 저장되지 않는 오류를 수정하였습니다
로그아웃 부분 커스텀 데코레이터를 사용하는 것으로 변경
기존 api 중 유저 정보를 확인하지 않은 api에 대해 유저 정보 확인 부분 추가
쿠키 시간 변경
로그인 여부 체크하는 api 추가
커스텀 데코레이터에 예외처리 부분 추가
유저 관련 예외처리에서 상태 코드 변경
createManyAndMapping에서 링크를 불러올 때 필터에 생성일 추가
```typescript
```
resolves #71

#71 Fix: 버그 수정

---

src/link/link.controller.ts
src/link/link.service.ts

링크의 제목 수정 기능을 개발하였습니다
link.controller.ts에 링크를 수정하도록 요청받는 api 개발
link.service.ts에 링크를 수정하는 함수 개발
```typescript
```
resolves #73

#73 Feat: 링크 제목 수정 기능

---

src/auth/auth.service.ts
src/auth/google.strategy.ts
src/auth/session.serializer.ts
src/user/user.service.ts

구글 프로필 업데이트 시 링킷에는 반영이 되지 않은 부분을 수정하였습니다
auth.service.ts에서 현재의 프로필과 저장된 프로필을 비교하는 부분 추가
user.service.ts에서 정보를 업데이트 하는 부분 추가
그 외는 서식 적용
```typescript
```
resolves #81

#81 Fix: 유저 정보 업데이트

---

src/link/link.controller.spec.ts
src/link/link.controller.ts
src/link/link.service.spec.ts
src/link/link.service.ts

태그 수정 기능을 추가하였습니다
태그 수정 기능에 대한 기본적인 테스트 코드를 추가하였습니다
링크 제목 수정의 method를 수정하였습니다
controller, service의 updateTags에 대한 기본적인 테스트 코드 추가
태그 수정을 요청받는 api 추가
태그 수정을 하는 service 함수 작성
링크 제목의 http method 변경
```typescript
```
resolves #74

#74 Feat: 링크의 태그 수정 기능

---

src/bucket/bucket.controller.ts
src/link/link.controller.spec.ts
src/link/link.controller.ts
src/link/link.module.ts
src/link/link.service.ts

링킷 페이지에서 링크를 추가하는 기능을 구현하였습니다.
- 링크 추가를 요청하는 api 구현
- 링크 저장 및 ai 요청 및 수정을 하는 기능 구현
- 링크 등록하는 로직에 대한 테스트 코드 구현
- bucket.controller쪽에서 console.log 삭제
resolves #83

#83 Feat: 링크 추가 기능

---

src/bucket/bucket.controller.ts
src/bucket/bucket.exception.ts
src/user/user.exception.ts

ai 응답이 오지 않았을 경우의 예외처리를 추가하였습니다
유저 예외처리 중 일부의 상태 코드를 변경하였습니다
resolves #87

#87 Refactor: 예외처리 추가

---

src/auth/google.strategy.ts

구글 로그인으로 받아오는 이름 정보를 이름만 받아오도록 변경하였습니다
```typescript
```
#90

#90 Refactor: 이름 저장방식 변경

---

src/bucket/bucket.controller.ts
src/bucket/bucket.exception.ts

AI호출 중 오류가 발생해 500 에러가 뜨는 경우에 대해 에러 처리를 추가하였습니다
#92

#92 Fix: ai 응답에 대한 에러처리 추가

---

src/bucket/bucket.controller.ts

error.response.status를 읽어올 수 없어서 분기문을 제거하였습니다
```typescript
```

PR dev to main

---

prisma/schema.prisma
src/bucket/bucket.service.ts
src/link/link.controller.spec.ts
src/link/link.controller.ts
src/link/link.service.spec.ts
src/link/link.service.ts

링크 단일 삭제/복수 삭제 기능을 위한 API를 구현하였습니다
- API 구현
- controller 테스트 코드 작성
- 관계와 링크를 지우는 service 작성
- service 테스트 코드 작성
바구니의 링크 수를 효츌적으로 업데이트 하기 위해 DB를 수정하고 바구니 정보 호출 시 관계 테이블에서의 수를 카운트 하는 방식으로 변경하였습니다.
- schema 수정
- linkCount를 사용하는 부분 bucketLink의 길이를 사용하도록 수정
resolves #86

#86 Feat: 링크 삭제 기능

---

src/link/link.controller.spec.ts
src/link/link.controller.ts
src/link/link.service.spec.ts
src/link/link.service.ts
src/utils/pagination.dto.ts

링크를 조회하는 API를 구현하였습니다.
- tag와 함께 요청받을 시 태그 필터링된 링크 결과 제공
- tag 없이 요청받을 시 전체 링크 제공
- 10개씩 페이지네이션하도록 구현
- 테스트코드 작성(성공시)
resolves #98

#98 Feat: 링크 조회 기능

---

src/app.controller.ts
src/app.module.ts
src/auth/auth.controller.ts
src/bucket/bucket.controller.ts
src/bucket/bucket.exception.ts
src/bucket/bucket.service.ts
src/bucket/dto/bucket.dto.ts
src/extension/extension.controller.spec.ts
src/extension/extension.controller.ts
src/extension/extension.module.ts
src/link/dto/link.dto.ts
src/link/link.controller.ts
src/link/link.service.ts
src/user/dto/user.dto.ts
src/user/user.controller.ts
src/user/user.exception.ts
src/utils/pagination.dto.ts

전체적인 컨트롤러에 대해 swagger 문서를 구체적으로 작성하였습니다
익스텐션에서 호출하는 api를 bucket에서 api/extension 경로로 분리하였습니다.
DTO 추가에 따라 타입이 일부 수정된 부분이 있습니다.
resolves #99

#99 Docs: swagger 수정

---

license
prisma/schema.prisma
src/bucket/dto/bucket.dto.ts
src/extension/extension.controller.ts
src/link/dto/link.dto.ts
src/link/link.controller.spec.ts
src/link/link.controller.ts
src/link/link.service.spec.ts
src/link/link.service.ts
src/utils/pagination.dto.ts

링크에 키워드를 추가하였습니다.
- 관련 DTO 수정
- 반환 형식 수정
- 스키마 수정
- 테스트코드 수정
- AI 호출 경로 수정
resolves #104

#104 Feat: 키워드 추출 추가로 인한 링크 기능 수정

---

src/bucket/bucket.controller.spec.ts
src/bucket/bucket.controller.ts
src/bucket/bucket.exception.ts
src/bucket/bucket.module.ts
src/bucket/bucket.service.ts
src/bucket/dto/bucket.dto.ts
src/link/dto/link.dto.ts
src/link/link.controller.spec.ts
src/link/link.controller.ts
src/link/link.service.ts
src/utils/pagination.dto.ts

검색 기능을 추가하였습니다.
- 바구니 제목 검색
- 링크의 제목/키워드 검색
bucket.controller.ts에서 검색을 위한 API 추가
bucket.service.ts에서 contains를 사용한 DB 조회
bucket controller 테스트 코드 추가
검색어가 없을 경우 발생할 예외 추가
link.controller.ts에서 검색을 위한 API 추가
link.service.ts에서 contains와 OR을 사용한 DB 조회
link controller 테스트 코드 추가
```typescript
```
resolves #111

#111 Feat: 검색 기능 추가

---

.gitignore
package.json
pnpm-lock.yaml
src/app.controller.ts
src/app.module.ts
src/auth/auth.controller.ts
src/link/link.controller.ts
src/main.ts
src/sentry.filter.ts
src/session/init.session.ts
tsconfig.json

sentry 설정을 추가하였습니다.
로그인시 리다이렉트 경로를 변경하였습니다.
link 조회의 method를 Get에서 Post로 변경하였습니다.
```typescript
```
resolves #113

#113 Feat: sentry 추가

---

Jenkinsfile_test_server

feat: Test 서버 전용 Jenkinsfile 작성

---

src/sentry.filter.ts

중복 응답을 전송하길 시도할 수 있어 Sentry filter에서 이미 응답을 전송했다면 응답을 전송하지 않도록 수정하였습니다.
```typescript
```
#123

#123 Fix: 중복된 응답으로 인한 에러 수정

---

src/bucket/bucket.service.ts

isShared의 값이 false로 항상 반환되도록 작성되어 있어 해당 bucket의 값으로 반영하도록 수정하였습니다.
```typescript
```
resolves #130

#130 Fix: 바구니 목록 조회 시 공유 상태가 제대로 전달되지 않는 부분 수정 

---

src/link/link.controller.ts
src/link/link.service.ts

GET에서 POST로 변경
body로 tag를 받도록 변경
```typescript
```
resolves #128

#128 Fix: 태그 필터 조회 API 수정

---

src/link/link.service.ts

링크가 처음 저장될 때 제목을 분류중으로 저장하도록 수정하였습니다.
```typescript
```
resolves #133

#133 Refactor: 링크와 바구니 처음 저장 시 분류중임을 표시하도록 변경
